package com.localhost.model;
// Generated 2017/6/17 下午 08:56:49 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CurrentStatus generated by hbm2java
 */
@Entity
@Table(name = "current_status", catalog = "dev_data")
public class CurrentStatus implements java.io.Serializable {

	private int statusId;
	private String statusName;

	public CurrentStatus() {
	}

	public CurrentStatus(String statusName) {
		this.statusName = statusName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "status_id", unique = true, nullable = false)
	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	@Column(name = "status_name", nullable = false, length = 5)
	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

}
