package com.localhost.model;
// Generated 2017/6/17 下午 08:56:49 by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name = "event", catalog = "dev_data")
public class Event implements java.io.Serializable {

	private EventId id;
	private String eventType;
	private String eventName;
	private String color;
	private String statusId;
	private String description;
	private String startDate;
	private String startTime;
	private String endDate;
	private String endTime;
	private Integer tuition;
	private Boolean allDay;
	private Integer charge;
	private String userId;

	public Event() {
	}

	public Event(EventId id, String statusId) {
		this.id = id;
		this.statusId = statusId;
	}

	public Event(EventId id, String eventType, String eventName, String color, String statusId, String description,
			String startDate, String startTime, String endDate, String endTime, Integer tuition, Boolean allDay,
			Integer charge, String userId) {
		this.id = id;
		this.eventType = eventType;
		this.eventName = eventName;
		this.color = color;
		this.statusId = statusId;
		this.description = description;
		this.startDate = startDate;
		this.startTime = startTime;
		this.endDate = endDate;
		this.endTime = endTime;
		this.tuition = tuition;
		this.allDay = allDay;
		this.charge = charge;
		this.userId = userId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "calendarId", column = @Column(name = "calendar_id", nullable = false, length = 4)),
			@AttributeOverride(name = "eventId", column = @Column(name = "event_id", nullable = false, length = 8)) })
	public EventId getId() {
		return this.id;
	}

	public void setId(EventId id) {
		this.id = id;
	}

	@Column(name = "event_type", length = 1)
	public String getEventType() {
		return this.eventType;
	}

	public void setEventType(String eventType) {
		this.eventType = eventType;
	}

	@Column(name = "event_name", length = 50)
	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	@Column(name = "color", length = 7)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "status_id", nullable = false, length = 1)
	public String getStatusId() {
		return this.statusId;
	}

	public void setStatusId(String statusId) {
		this.statusId = statusId;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "start_date", length = 10)
	public String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	@Column(name = "start_time", length = 5)
	public String getStartTime() {
		return this.startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	@Column(name = "end_date", length = 10)
	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	@Column(name = "end_time", length = 5)
	public String getEndTime() {
		return this.endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	@Column(name = "tuition")
	public Integer getTuition() {
		return this.tuition;
	}

	public void setTuition(Integer tuition) {
		this.tuition = tuition;
	}

	@Column(name = "all_day")
	public Boolean getAllDay() {
		return this.allDay;
	}

	public void setAllDay(Boolean allDay) {
		this.allDay = allDay;
	}

	@Column(name = "charge")
	public Integer getCharge() {
		return this.charge;
	}

	public void setCharge(Integer charge) {
		this.charge = charge;
	}

	@Column(name = "user_id", length = 6)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
