package com.localhost.model;
// Generated 2017/6/17 下午 08:56:49 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Member generated by hbm2java
 */
@Entity
@Table(name = "member", catalog = "dev_data")
public class Member implements java.io.Serializable {

	private String memberId;
	private String firstName;
	private String lastName;
	private String calendarId;
	private String address;
	private String birthday;
	private String email;
	private String image;
	private String phone;
	private Integer tuition;
	private String lastPaymentDate;
	private String expectPaymentDate;
	private String paymentAmountId;
	private Integer paymentCountNumber;
	private String paymentStatusId;
	private String statusId;
	private String titleId;
	private String registerTime;
	private String userId;

	public Member() {
	}

	public Member(String memberId) {
		this.memberId = memberId;
	}

	public Member(String memberId, String firstName, String lastName, String calendarId, String address,
			String birthday, String email, String image, String phone, Integer tuition, String lastPaymentDate,
			String expectPaymentDate, String paymentAmountId, Integer paymentCountNumber, String paymentStatusId,
			String statusId, String titleId, String registerTime, String userId) {
		this.memberId = memberId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.calendarId = calendarId;
		this.address = address;
		this.birthday = birthday;
		this.email = email;
		this.image = image;
		this.phone = phone;
		this.tuition = tuition;
		this.lastPaymentDate = lastPaymentDate;
		this.expectPaymentDate = expectPaymentDate;
		this.paymentAmountId = paymentAmountId;
		this.paymentCountNumber = paymentCountNumber;
		this.paymentStatusId = paymentStatusId;
		this.statusId = statusId;
		this.titleId = titleId;
		this.registerTime = registerTime;
		this.userId = userId;
	}

	@Id

	@Column(name = "member_id", unique = true, nullable = false, length = 6)
	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	@Column(name = "first_name", length = 10)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 10)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "calendar_id", length = 4)
	public String getCalendarId() {
		return this.calendarId;
	}

	public void setCalendarId(String calendarId) {
		this.calendarId = calendarId;
	}

	@Column(name = "address", length = 40)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "birthday", length = 10)
	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	@Column(name = "email", length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "image", length = 20)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "phone", length = 11)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "tuition")
	public Integer getTuition() {
		return this.tuition;
	}

	public void setTuition(Integer tuition) {
		this.tuition = tuition;
	}

	@Column(name = "last_payment_date", length = 10)
	public String getLastPaymentDate() {
		return this.lastPaymentDate;
	}

	public void setLastPaymentDate(String lastPaymentDate) {
		this.lastPaymentDate = lastPaymentDate;
	}

	@Column(name = "expect_payment_date", length = 10)
	public String getExpectPaymentDate() {
		return this.expectPaymentDate;
	}

	public void setExpectPaymentDate(String expectPaymentDate) {
		this.expectPaymentDate = expectPaymentDate;
	}

	@Column(name = "payment_amount_id", length = 2)
	public String getPaymentAmountId() {
		return this.paymentAmountId;
	}

	public void setPaymentAmountId(String paymentAmountId) {
		this.paymentAmountId = paymentAmountId;
	}

	@Column(name = "payment_count_number")
	public Integer getPaymentCountNumber() {
		return this.paymentCountNumber;
	}

	public void setPaymentCountNumber(Integer paymentCountNumber) {
		this.paymentCountNumber = paymentCountNumber;
	}

	@Column(name = "payment_status_id", length = 1)
	public String getPaymentStatusId() {
		return this.paymentStatusId;
	}

	public void setPaymentStatusId(String paymentStatusId) {
		this.paymentStatusId = paymentStatusId;
	}

	@Column(name = "status_id", length = 1)
	public String getStatusId() {
		return this.statusId;
	}

	public void setStatusId(String statusId) {
		this.statusId = statusId;
	}

	@Column(name = "title_id", length = 2)
	public String getTitleId() {
		return this.titleId;
	}

	public void setTitleId(String titleId) {
		this.titleId = titleId;
	}

	@Column(name = "register_time")
	public String getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(String registerTime) {
		this.registerTime = registerTime;
	}

	@Column(name = "user_id", length = 6)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
