package com.localhost.model;
// Generated 2017/6/17 下午 08:56:49 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PaymentRecordLog generated by hbm2java
 */
@Entity
@Table(name = "payment_record_log", catalog = "dev_data")
public class PaymentRecordLog implements java.io.Serializable {

	private Long id;
	private String memberId;
	private Integer amount;
	private String paymentDate;

	public PaymentRecordLog() {
	}

	public PaymentRecordLog(String memberId, Integer amount, String paymentDate) {
		this.memberId = memberId;
		this.amount = amount;
		this.paymentDate = paymentDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "member_id", length = 6)
	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	@Column(name = "amount")
	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	@Column(name = "payment_date", length = 10)
	public String getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(String paymentDate) {
		this.paymentDate = paymentDate;
	}

}
