package com.localhost.model;
// Generated 2017/6/17 下午 08:56:49 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PaymentStatus generated by hbm2java
 */
@Entity
@Table(name = "payment_status", catalog = "dev_data")
public class PaymentStatus implements java.io.Serializable {

	private Long paymentStatusId;
	private String paymentStatusName;

	public PaymentStatus() {
	}

	public PaymentStatus(String paymentStatusName) {
		this.paymentStatusName = paymentStatusName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "payment_status_id", unique = true, nullable = false)
	public Long getPaymentStatusId() {
		return this.paymentStatusId;
	}

	public void setPaymentStatusId(Long paymentStatusId) {
		this.paymentStatusId = paymentStatusId;
	}

	@Column(name = "payment_status_name", nullable = false, length = 5)
	public String getPaymentStatusName() {
		return this.paymentStatusName;
	}

	public void setPaymentStatusName(String paymentStatusName) {
		this.paymentStatusName = paymentStatusName;
	}

}
