package com.localhost.model;
// Generated 2017/6/17 下午 08:56:49 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PersonalTitle generated by hbm2java
 */
@Entity
@Table(name = "personal_title", catalog = "dev_data")
public class PersonalTitle implements java.io.Serializable {

	private Long titleId;
	private String titleName;

	public PersonalTitle() {
	}

	public PersonalTitle(String titleName) {
		this.titleName = titleName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "title_id", unique = true, nullable = false)
	public Long getTitleId() {
		return this.titleId;
	}

	public void setTitleId(Long titleId) {
		this.titleId = titleId;
	}

	@Column(name = "title_name", length = 10)
	public String getTitleName() {
		return this.titleName;
	}

	public void setTitleName(String titleName) {
		this.titleName = titleName;
	}

}
