package com.localhost.model;
// Generated 2017/6/17 下午 08:56:49 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserStatus generated by hbm2java
 */
@Entity
@Table(name = "user_status", catalog = "dev_data")
public class UserStatus implements java.io.Serializable {

	private String statusId;
	private String statusName;

	public UserStatus() {
	}

	public UserStatus(String statusId) {
		this.statusId = statusId;
	}

	public UserStatus(String statusId, String statusName) {
		this.statusId = statusId;
		this.statusName = statusName;
	}

	@Id

	@Column(name = "status_id", unique = true, nullable = false, length = 2)
	public String getStatusId() {
		return this.statusId;
	}

	public void setStatusId(String statusId) {
		this.statusId = statusId;
	}

	@Column(name = "status_name", length = 5)
	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

}
