package com.localhost.model;
// Generated 2017/6/17 下午 08:56:49 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "user_role", catalog = "dev_data")
public class UserRole implements java.io.Serializable {

	private String roleId;
	private String roleType;

	public UserRole() {
	}

	public UserRole(String roleId, String roleType) {
		this.roleId = roleId;
		this.roleType = roleType;
	}

	@Id

	@Column(name = "role_id", unique = true, nullable = false, length = 2)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_type", nullable = false, length = 10)
	public String getRoleType() {
		return this.roleType;
	}

	public void setRoleType(String roleType) {
		this.roleType = roleType;
	}

}
